import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { AIAllocationResult } from "@/services/aiAllocationService";
import { ArrowRight, AlertTriangle, CheckCircle2, TrendingUp, AlertOctagon, Clock, ShieldAlert } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface OptimizationReviewDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    plan: AIAllocationResult | null;
    onApply: () => void;
    isApplying: boolean;
}

export function OptimizationReviewDialog({ open, onOpenChange, plan, onApply, isApplying }: OptimizationReviewDialogProps) {
    if (!plan) return null;

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-3xl bg-white text-gray-900 max-h-[90vh] flex flex-col p-0 gap-0 overflow-hidden">
                <DialogHeader className="px-6 py-5 border-b border-gray-100 bg-gray-50/50">
                    <DialogTitle className="flex items-center gap-2.5 text-xl font-bold text-gray-900">
                        <div className="p-1.5 bg-indigo-100 rounded-lg">
                            <CheckCircle2 className="w-5 h-5 text-indigo-600" />
                        </div>
                        AI Optimization Plan
                    </DialogTitle>
                    <DialogDescription className="text-gray-500 ml-11">
                        Review the suggested allocation changes generated by the AI engine.
                    </DialogDescription>
                </DialogHeader>

                <ScrollArea className="flex-1 px-6 py-6">
                    <div className="space-y-6">
                        {/* Summary */}
                        <div className="bg-gradient-to-r from-indigo-50 to-white border border-indigo-100 p-4 rounded-xl text-sm text-indigo-900 shadow-sm">
                            <div className="flex gap-2">
                                <span className="font-semibold whitespace-nowrap">Executive Summary:</span>
                                <span className="text-indigo-800/90 leading-relaxed">{plan.summary}</span>
                            </div>
                        </div>

                        {/* Risks */}
                        {plan.risks.length > 0 && (
                            <Card className="border-amber-200 bg-amber-50/30 shadow-sm">
                                <CardHeader className="pb-2 pt-4 px-4">
                                    <CardTitle className="text-sm font-bold flex items-center gap-2 text-amber-800">
                                        <AlertTriangle className="w-4 h-4" /> Risks Identified
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="px-4 pb-4">
                                    <ul className="space-y-2">
                                        {plan.risks.map((risk, idx) => (
                                            <li key={idx} className="text-sm text-amber-900/80 flex items-start gap-2">
                                                <span className="block w-1.5 h-1.5 mt-1.5 rounded-full bg-amber-400 flex-shrink-0" />
                                                {risk}
                                            </li>
                                        ))}
                                    </ul>
                                </CardContent>
                            </Card>
                        )}

                        {/* Timeline Analysis */}
                        {plan.timeline && (plan.timeline.onTrackProjects || plan.timeline.atRiskProjects || plan.timeline.recommendedShifts || plan.timeline.urgentActions) && (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <Card className="border-emerald-100 bg-emerald-50/30 shadow-sm">
                                    <CardHeader className="pb-2 pt-4 px-4">
                                        <CardTitle className="text-sm font-bold flex items-center gap-2 text-emerald-800">
                                            <TrendingUp className="w-4 h-4" /> On Track
                                        </CardTitle>
                                    </CardHeader>
                                    <CardContent className="px-4 pb-4">
                                        {plan.timeline.onTrackProjects && plan.timeline.onTrackProjects.length > 0 ? (
                                            <ul className="space-y-1.5">
                                                {plan.timeline.onTrackProjects.map((project, idx) => (
                                                    <li key={`onTrack-${idx}`} className="text-xs font-medium text-emerald-700 flex items-center gap-2">
                                                        <CheckCircle2 className="w-3 h-3 text-emerald-500" />
                                                        {project}
                                                    </li>
                                                ))}
                                            </ul>
                                        ) : (
                                            <p className="text-xs text-gray-400 italic">No projects currently on track</p>
                                        )}
                                    </CardContent>
                                </Card>

                                <Card className="border-rose-100 bg-rose-50/30 shadow-sm">
                                    <CardHeader className="pb-2 pt-4 px-4">
                                        <CardTitle className="text-sm font-bold flex items-center gap-2 text-rose-800">
                                            <AlertOctagon className="w-4 h-4" /> At Risk
                                        </CardTitle>
                                    </CardHeader>
                                    <CardContent className="px-4 pb-4">
                                        {plan.timeline.atRiskProjects && plan.timeline.atRiskProjects.length > 0 ? (
                                            <ul className="space-y-1.5">
                                                {plan.timeline.atRiskProjects.map((project, idx) => (
                                                    <li key={`risk-${idx}`} className="text-xs font-medium text-rose-700 flex items-center gap-2">
                                                        <ShieldAlert className="w-3 h-3 text-rose-500" />
                                                        {project}
                                                    </li>
                                                ))}
                                            </ul>
                                        ) : (
                                            <p className="text-xs text-gray-400 italic">No projects at risk</p>
                                        )}
                                    </CardContent>
                                </Card>
                            </div>
                        )}

                        {/* Suggested Moves */}
                        <div className="space-y-3">
                            <h4 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                                <div className="w-1 h-4 bg-indigo-600 rounded-full" />
                                Suggested Moves ({plan.moves.length})
                            </h4>
                            <div className="space-y-3">
                                {plan.moves.map((move, idx) => (
                                    <div key={idx} className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow group">
                                        <div className="flex items-center justify-between mb-3">
                                            <div className="flex items-center gap-3">
                                                <Badge variant="outline" className="bg-gray-50 font-semibold text-gray-700 border-gray-200 px-2.5 py-0.5">
                                                    {move.memberName}
                                                </Badge>
                                                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-indigo-400 transition-colors" />
                                                <span className="text-sm font-bold text-gray-900">{move.targetTeamName}</span>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                {move.priority && (
                                                    <Badge className={`text-[10px] font-semibold px-2 py-0.5 ${move.priority === 'critical' ? 'bg-rose-100 text-rose-700 hover:bg-rose-200 border-rose-200' :
                                                            move.priority === 'high' ? 'bg-orange-100 text-orange-700 hover:bg-orange-200 border-orange-200' :
                                                                move.priority === 'medium' ? 'bg-amber-100 text-amber-700 hover:bg-amber-200 border-amber-200' :
                                                                    'bg-slate-100 text-slate-600 hover:bg-slate-200 border-slate-200'
                                                        }`}>
                                                        {move.priority.toUpperCase()}
                                                    </Badge>
                                                )}
                                            </div>
                                        </div>
                                        <div className="bg-gray-50/50 rounded-lg p-3 border border-gray-100/50">
                                            <p className="text-xs text-gray-600 italic leading-relaxed">"{move.reasoning}"</p>
                                            {move.expectedImpact && (
                                                <div className="mt-2 flex items-center gap-1.5 text-xs font-medium text-indigo-600">
                                                    <TrendingUp className="w-3 h-3" />
                                                    Impact: {move.expectedImpact}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                ))}
                                {plan.moves.length === 0 && (
                                    <div className="text-center py-12 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                                        <CheckCircle2 className="w-8 h-8 text-gray-300 mx-auto mb-2" />
                                        <p className="text-sm text-gray-500 font-medium">No moves suggested</p>
                                        <p className="text-xs text-gray-400">Current allocation is optimal</p>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </ScrollArea>

                <DialogFooter className="px-6 py-4 border-t border-gray-100 bg-gray-50/50">
                    <Button variant="outline" onClick={() => onOpenChange(false)} className="border-gray-200 hover:bg-white hover:text-gray-900">Cancel</Button>
                    <Button onClick={onApply} disabled={isApplying || plan.moves.length === 0} className="bg-indigo-600 hover:bg-indigo-700 shadow-sm px-6">
                        {isApplying ? (
                            <>
                                <Clock className="w-4 h-4 mr-2 animate-spin" />
                                Applying Changes...
                            </>
                        ) : (
                            'Apply Optimization Plan'
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
