import jsPDF from 'jspdf';
import { Project } from '@/types/allocation';
import { generateProjectReportSummary } from '@/services/aiService';

export async function generateProjectReport(project: Project) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text(`Project Report: ${project.name}`, margin, 30);

    // Status Badge
    doc.setFontSize(10);
    doc.setFillColor(0, 217, 255); // #00D9FF
    doc.rect(margin, 35, 20, 6, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('ACTIVE', margin + 3, 39);

    // AI Summary Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text('Executive Summary (AI Generated)', margin, 55);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generating insights...', margin, 65);

    const summary = await generateProjectReportSummary(project);

    // Clear "Generating..."
    doc.setFillColor(255, 255, 255);
    doc.rect(margin, 60, pageWidth - margin * 2, 20, 'F');

    doc.setFont('helvetica', 'normal');
    const splitSummary = doc.splitTextToSize(summary, pageWidth - margin * 2);
    doc.text(splitSummary, margin, 65);

    let yPos = 65 + splitSummary.length * 5 + 10;

    // Team Overview
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Team Structure', margin, yPos);
    yPos += 10;

    project.teams.forEach((team) => {
        // Check page break
        if (yPos > 270) {
            doc.addPage();
            yPos = 30;
        }

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(team.name, margin, yPos);
        yPos += 7;

        if (team.members.length === 0) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'italic');
            doc.text('No members assigned.', margin + 5, yPos);
            yPos += 10;
        } else {
            team.members.forEach((member) => {
                if (yPos > 280) {
                    doc.addPage();
                    yPos = 30;
                }
                doc.setFontSize(10);
                doc.setFont('helvetica', 'normal');
                doc.text(`• ${member.name} (${member.role})`, margin + 5, yPos);
                doc.setFontSize(8);
                doc.setTextColor(100);
                doc.text(`   Load: ${member.currentWorkload}h / ${member.maxCapacity}h | ${member.skills.slice(0, 3).join(', ')}`, margin + 5, yPos + 4);
                doc.setTextColor(0);
                yPos += 10;
            });
        }
        yPos += 5;
    });

    // Requirements Status
    if (yPos > 250) {
        doc.addPage();
        yPos = 30;
    }

    if (project.requirements) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Resourcing Requirements', margin, yPos);
        yPos += 10;

        project.requirements.forEach(req => {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            // Calculate actual count
            const currentCount = project.teams.reduce((acc, t) =>
                acc + t.members.filter(m => m.role === req.role).length, 0
            );
            const status = currentCount >= req.count ? "MET" : "PENDING";
            const color = status === "MET" ? [0, 150, 0] : [200, 0, 0];

            doc.setTextColor(color[0], color[1], color[2]);
            doc.text(`[${status}]`, margin, yPos);
            doc.setTextColor(0, 0, 0);
            doc.text(`${req.role}: ${currentCount} / ${req.count}`, margin + 25, yPos);
            yPos += 7;
        });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by AllocateX AI - Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' });
    }

    doc.save(`${project.name.replace(/\s+/g, '_')}_Report.pdf`);
}
